[project]
name = "MathRunner"
version = "0.1.0"
requires-python = "==3.13.*"

dependencies = [
    "numexpr==2.10.0",
    "numpy==2.2.3",
    "pygame==2.6.1",
    "pyqtgraph==0.13.7",
    "pyside6==6.8.2.1",
]

[dependency-groups]
dev = [
    "sphinx==8.2.3",
]

[tool.uv]
package = true
