#------------------------------------------------------------------------------#
# ./fvelgame/resources/Makefile

default:
	  make -C games

clean:

distclean: 

.PHONY: clean distclean

#------------------------------------------------------------------------------#
